# Generated by Django 5.0.1 on 2025-11-10 11:10

import rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='session_name',
            field=models.CharField(default=rooms.models.generate_session_name, max_length=255),
        ),
    ]
